name: app_realtime
description: Reusable websocket realtime client and event stream for FOM apps.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  app_core:
    path: ../app_core
  app_logger:
    path: ../app_logger
  app_network:
    path: ../app_network
  equatable: ^2.0.8
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
